name: Build Blog

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run build:blog

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: atualizar blog [skip ci]"
          commit_user_name: "Fiter Bot"
          commit_user_email: "bot@fiter.com.br"
